name: Backend CI/CD

on:
  push:
    branches:
      - main
    #paths:
    #  - 'backend/**'

jobs:
  test-lambda:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest

    steps: 

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: 'backend'

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install Dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt
      working-directory: ./backend

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: 'us-east-1'
        role-to-assume: ${{ secrets.ROLE_TO_ASSUME }} #setup role as secret

    - name: Test Lambda with pytest
      shell: bash
      run: |
        cd backend
      #  pytest 'some test'
      working-directory: ./backend

    - name: Package Lambda function
      if: ${{ job.status == 'success' }}
      run: |
        cd backend
        zip -r9 count.zip count.py
      working-directory: ./backend

#------------------------------------------------------------------------------

