name : Upload resume website to S3

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1' 

    - name: S3 sync
      run: aws s3 sync ./resume3.0 s3://cloud-resume-challenge-bucket5673442 --delete
        
    - name: Cloudfront create-invalidation
      run: aws cloudfront create-invalidation --distribution-id E25PTMM0VI4A49 --paths "/*"       
        
        