

name: Backend CI/CD

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install aws-sam-cli
      
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/IaC" >> $GITHUB_ENV

      - name: Run tests
        run: pytest IaC/tests/unit/ 
        env:
          AWS_DEFAULT_REGION: 'us-east-1'

      - name: SAM Build
        run: sam build -t IaC/template.yaml

      - name: SAM Package
        run: |
          sam package --region us-east-1 --template-file .aws-sam/build/template.yaml --output-template-file packaged.yaml --s3-bucket ${{ secrets.AWS_S3_BUCKET }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'

      - name: SAM Deploy
        run: |
          sam deploy --template-file packaged.yaml --stack-name IaC --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND --region us-east-1 --s3-bucket ${{ secrets.AWS_S3_BUCKET }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      

      - name: Get API URL 2
        id: get_api_url
        run: |
          API_URL=$(aws cloudformation describe-stacks --stack-name IaC --region us-east-1 --query "Stacks[0].Outputs[?OutputKey=='HelloWorldApi'].OutputValue" --output text)
          echo "::set-output name=api_url::$API_URL"
